FROM nvcr.io/nvidia/tensorflow:20.12-tf2-py3

WORKDIR /
RUN pip3 install --no-cache-dir git+https://github.com/onnx/onnx-tensorflow
RUN pip3 install --no-cache-dir git+https://github.com/onnx/tensorflow-onnx

# Requirements for testing with our pipeline
RUN apt-get update && apt-get install -y libsndfile1
COPY training/ /Scribosermo/training/
RUN pip3 install --no-cache-dir -e /Scribosermo/training/

CMD ["/bin/bash"]
