FROM nvcr.io/nvidia/tensorflow:20.03-tf1-py3

# Install basic packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    sox libsox-dev

# Build kenlm
RUN mkdir /DeepSpeech/ /DeepSpeech/native_client/ \
    && cd /DeepSpeech/native_client/ \
    && git clone --depth 1 https://github.com/kpu/kenlm \
    && cd kenlm \
    && mkdir -p build \
    && cd build \
    && cmake .. \
    && make -j 4

# Install required python packages
COPY . /DeepSpeech/
RUN pip3 install --no-cache-dir /DeepSpeech/

# Tool to convert output graph for inference
RUN python3 /DeepSpeech/util/taskcluster.py --source tensorflow --artifact convert_graphdef_memmapped_format --branch r1.15 --target .

WORKDIR /DeepSpeech/
CMD ["/bin/bash"]
