import os
import tarfile
import urllib

from progressist import ProgressBar
from vctube import VCtube

# ==================================================================================================


def download_youtube_playlist(output_dir, playlist_url, lang):
    vc = VCtube(output_dir, playlist_url, lang)
    vc.download_audio()
    vc.download_captions(skip_autogenerated=True)
    vc.audio_split(parallel=True)


# ==================================================================================================


def download_and_extract(link, target_path):
    path = os.path.join(target_path, "tmp.tar.gz")
    pbar = ProgressBar(template="Download |{animation}| {done:B}/{total:B}")
    urllib.request.urlretrieve(link, path, reporthook=pbar.on_urlretrieve)

    tf = tarfile.open(path)
    tf.extractall(path=target_path)
    os.remove(path)
